import streamlit as st
import openai
from PIL import Image
import os
from dotenv import load_dotenv
import base64
import io

# .envの読み込み
load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")

st.set_page_config(page_title="StreetCasting AI MVP", layout="wide")

st.title("📸 StreetCasting AI")
st.subheader("何気ない風景を、最高のポートレートスタジオに。")

# サイドバー設定
st.sidebar.header("Settings")
model_gender = st.sidebar.selectbox("Gender", ["Random", "Female", "Male", "Non-binary"])
model_age = st.sidebar.slider("Age", 18, 60, 25)
model_style = st.sidebar.text_input("Style / Outfit", "Chic, casual, professional")

# メイン画面
uploaded_file = st.file_uploader("写真をアップロードしてください", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    col1, col2 = st.columns(2)
    
    with col1:
        st.image(uploaded_file, caption="Uploaded Image", use_container_width=True)
    
    # ユーザーが背景の説明を補足できるようにテキストエリアを追加
    bg_info = st.text_area("背景の補足説明 (任意)", placeholder="例: 暗いギャラリー、スポットライト、木製の柱...")

    if st.button("モデルを合成する (Generate)"):
        with st.spinner("gpt-image-2 が画像を生成中..."):
            try:
                # gpt-image-2 へのリクエスト
                # ※お客様のAPI環境が image_url 形式の入力を受け付ける想定
                prompt = f"Background: {bg_info}. " \
                         f"Subject: A {model_age}-year-old {model_gender} model wearing {model_style}. " \
                         f"Action: Professional portrait pose, perfectly integrated into the environment. " \
                         f"Style: Cinematic, high-quality photography, matching light and shadows."
                
                response = openai.images.generate(
                    model="gpt-image-2",  # エンジン名を厳守
                    prompt=prompt,
                    # 画像パスやURLの渡し方はお客様のカスタムエンドポイントの仕様に従ってください
                    extra_body={
                        "input_image_path": uploaded_file.name # 仮のパラメータ名
                    } if hasattr(uploaded_file, 'name') else {}
                )
                
                generated_image_url = response.data[0].url
                
                with col2:
                    st.image(generated_image_url, caption="Generated by gpt-image-2", use_container_width=True)
                    st.success("生成が完了しました！")
                    
            except Exception as e:
                st.error(f"エラーが発生しました: {e}")

else:
    st.info("左側のカラムに画像をアップロードして開始してください。")
